kind: Service
apiVersion: v1
metadata:
  labels:
    app: example-test02
  name: example-test02
  namespace: default
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: example-test02
  type: ClusterIP

